// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanalMarket.Context;

#nullable disable

namespace SanalMarket.Migrations
{
    [DbContext(typeof(SanalMarketDbContext))]
    [Migration("20230821214732_Second_ProductViewModelId")]
    partial class Second_ProductViewModelId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanalMarket.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageName = "ekmek.jpg",
                            Name = "Ekmek",
                            Price = 5m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            ImageName = "peynir.jpg",
                            Name = "Peynir",
                            Price = 100m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            ImageName = "zeytin.jpg",
                            Name = "Zeytin",
                            Price = 50m,
                            StockQuantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
